// @generated - This file is generated by esquema-codegen (forked from atrium-codegen). DO NOT EDIT.
//!Definitions for the `com.crabdance.nandi.post` namespace.
use atrium_api::types::TryFromUnknown;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct RecordData {
    ///The main content of the blog post in markdown
    pub content: String,
    pub created_at: atrium_api::types::string::Datetime,
    ///Whether the post is published or draft
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub published: core::option::Option<bool>,
    ///Optional summary/excerpt of the post
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub summary: core::option::Option<String>,
    ///Tags for categorizing the post
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub tags: core::option::Option<Vec<String>>,
    ///The title of the blog post
    pub title: String,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub updated_at: core::option::Option<atrium_api::types::string::Datetime>,
}
pub type Record = atrium_api::types::Object<RecordData>;
impl From<atrium_api::types::Unknown> for RecordData {
    fn from(value: atrium_api::types::Unknown) -> Self {
        Self::try_from_unknown(value).unwrap()
    }
}
