// @generated - This file is generated by esquema-codegen (forked from atrium-codegen). DO NOT EDIT.
//!Definitions for the `com.crabdance.nandi` namespace.
pub mod post;
#[derive(Debug)]
pub struct Post;
impl atrium_api::types::Collection for Post {
    const NSID: &'static str = "com.crabdance.nandi.post";
    type Record = post::Record;
}
