// @generated - This file is generated by esquema-codegen (forked from atrium-codegen). DO NOT EDIT.
//!A collection of known record types.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "$type")]
pub enum KnownRecord {
    #[serde(rename = "com.crabdance.nandi.post")]
    CodegenComCrabdanceNandiPost(
        Box<crate::codegen::com::crabdance::nandi::post::Record>,
    ),
}
impl From<crate::codegen::com::crabdance::nandi::post::Record> for KnownRecord {
    fn from(record: crate::codegen::com::crabdance::nandi::post::Record) -> Self {
        KnownRecord::CodegenComCrabdanceNandiPost(Box::new(record))
    }
}
impl From<crate::codegen::com::crabdance::nandi::post::RecordData> for KnownRecord {
    fn from(
        record_data: crate::codegen::com::crabdance::nandi::post::RecordData,
    ) -> Self {
        KnownRecord::CodegenComCrabdanceNandiPost(Box::new(record_data.into()))
    }
}
impl Into<atrium_api::types::Unknown> for KnownRecord {
    fn into(self) -> atrium_api::types::Unknown {
        atrium_api::types::TryIntoUnknown::try_into_unknown(&self).unwrap()
    }
}
